version: "3.1"
services:
  database:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=grades"
      - "POSTGRES_USER=grades-user"
      - "POSTGRES_PASSWORD=iamgroot"